{% set name = "openbte" %}
{% set version = "0.9.40" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number : 0      
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - alabaster
    - deepdish
    - future
    - ipython
    - matplotlib
    - mpi4py==2.0.0
    - numpy
    - pip
    - python
    - pyvtk
    - scipy
    - shapely
    - sparse
    - unittest2
    - gmsh  
    - lapack  
  run:
    - alabaster
    - deepdish
    - future
    - ipython
    - matplotlib
    - mpi4py==2.0.0
    - numpy
    - python
    - pyvtk
    - scipy
    - shapely
    - sparse
    - unittest2
    - gmsh
    - lapack  

test:
  imports:
    - openbte

about:
  home: www.openbte.org
  license: GPLv2
  license_family: GPL2
  license_file: ../LICENSE 
  summary: Boltzmann Transport Equation for Phonons
  doc_url: https://romanodev.github.io/OpenBTE/_build/html/index.html
  dev_url: https://github.com/romanodev/OpenBTE
  description: On Windows you'll have to install MSMPI. For all platform the full command is: conda install -c guyer/label/hidden -c conda-forge -c gromano openbte

extra:
  recipe-maintainers:
    - romanodev
