
package:
  name: "openbte"
  version: "0.9.73"

source:
  url: ../dist/openbte-0.9.73.tar.gz

build:
        
  number: 4
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - alabaster
    - deepdish
    - future
    - ipython
    - matplotlib
    - mpi4py==2.0.0
    - networkx
    - numpy
    - pip
    - python
    - pyvtk
    - scipy
    - shapely
    - sparse
    - twisted  
    - termcolor
    - unittest2
  run:
    - alabaster
    - deepdish
    - future
    - ipython
    - matplotlib
    - mpi4py==2.0.0
    - networkx
    - numpy
    - python
    - pyvtk
    - scipy
    - twisted  
    - shapely
    - sparse
    - termcolor
    - unittest2
    - gmsh==3.0.6
    - pyqt

test:
  imports:
    - openbte
about:
  home: The package home page
  license: GPLv2
  license_family: GPL2
  license_file: 
  summary: Boltzmann Transport Equation for Phonons
  doc_url: 
  dev_url:
  description: For Windows you'll need to install MSMPI. Install with conda install -c conda-forge -c gromano openbte

extra:
  recipe-maintainers:
    - romanodev
