
package:
  name: "openbte"
  version: "1.16"

source:
  url: ../dist/openbte-1.13.tar.gz
build:
        
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - deepdish
    - mpi4py
    - numpy
    - pip
    - plotly
    - python >=3.6
    - pyvtk
    - scipy
    - gmsh
    - shapely
    - twisted  
    - pandas  
    - termcolor
    - unittest2
    - googledrivedownloader
    - suitesparse
    - swig  
    - scikit-umfpack
  run:
    - deepdish
    - future
    - mpi4py
    - plotly
    - numpy
    - googledrivedownloader
    - python >=3.6
    - pyvtk
    - scipy
    - shapely
    - termcolor
    - unittest2
    - gmsh
    - pyqt
    - swig  
    - suitesparse
    - scikit-umfpack

test:
  imports:
    - openbte
about:
  home: The package home page
  license: GPLv2
  license_family: GPL2
  license_file: 
  summary: Boltzmann Transport Equation for Phonons
  doc_url: 
  dev_url:
  description: For Windows you'll need to install MSMPI. Install with conda install -c conda-forge -c gromano openbte

extra:
  recipe-maintainers:
    - romanodev
