package:
    name: openbte
    version: 0.9.26 

source:
    url: ../dist/openbte-0.9.26.tar.gz

requirements:
    build:
        - python
    run:
        - python

test:
    imports:
        - openbte
