theme: jekyll-theme-cayman
publications_url: "https://romanodev.github.io/OpenBTE/publications"
database_url: "https://romanodev.github.io/OpenBTE/database_url: "
manual_url: "https://romanodev.github.io/OpenBTE/manual_url: "
