{% set name = "openbte" %}
{% set version = "0.9.39" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number: 2
  noarch: python
  entry_points:
    - openbte=openbte.__main__:main
    - shengbte2openbte=openbte.shengbte2openbte:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - alabaster
    - deepdish
    - future
    - ipython
    - matplotlib
    - mpi4py
    - networkx
    - numpy
    - pip
    - python
    - pyvtk
    - scipy
    - shapely
    - sparse
    - termcolor
    - twisted
    - unittest2
  run:
    - alabaster
    - deepdish
    - future
    - ipython
    - matplotlib
    - mpi4py
    - networkx
    - numpy
    - python
    - pyvtk
    - scipy
    - shapely
    - sparse
    - termcolor
    - twisted
    - unittest2

test:
  imports:
    - openbte
about:
  home: The package home page
  license: GPLv2
  license_family: GPL2
  license_file: 
  summary: Boltzmann Transport Equation for Phonons
  doc_url: 
  dev_url:
  description: For Windows you'll beed to install MSMPI. Install with    conda install -c guyer/label/hidden -c conda-forge -c gromano openbte

extra:
  recipe-maintainers:
    - romanodev
