# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/gromano/OpenBTE/recipe, last modified Mon Aug  5 09:18:54 2019
# ------------------------------------------------

package:
    name: openbte
    version: 0.9.59
source:
    url: ../dist/openbte-0.9.59.tar.gz
build:
    noarch: python
    number: '1'
    script: '/home/gromano/anaconda3/conda-bld/openbte_1565070116025/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . --no-deps --ignore-installed -vvv '
    string: pyh5ca1d4c_1
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - alabaster 0.7.12 py_0
        - appdirs 1.4.3 py_1
        - asn1crypto 0.24.0 py35_3
        - attrs 19.1.0 py_0
        - automat 0.7.0 py_1
        - backcall 0.1.0 py_0
        - blas 1.1 openblas
        - blosc 1.17.0 he1b5a44_0
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2018.8.24 py35_1001
        - cffi 1.11.5 py35h5e8e0c9_1
        - constantly 15.1.0 py_0
        - cryptography 2.3.1 py35hdffb7b8_0
        - cryptography-vectors 2.3.1 py35_0
        - cycler 0.10.0 py_1
        - dbus 1.13.2 h714fa37_1
        - decorator 4.4.0 py_0
        - deepdish 0.3.4 py_3
        - expat 2.2.5 he1b5a44_1003
        - fontconfig 2.13.1 he4413a7_1000
        - freetype 2.10.0 he983fc9_0
        - future 0.16.0 py35_2
        - geos 3.6.2 heeff764_2
        - gettext 0.19.8.1 hc5be6a0_1002
        - glib 2.56.2 had28632_1001
        - gst-plugins-base 1.14.0 hbbd80ab_1
        - gstreamer 1.14.0 hb453b48_1
        - hdf5 1.10.2 hc401514_3
        - hyperlink 17.3.1 py_0
        - icu 58.2 hf484d3e_1000
        - idna 2.7 py35_2
        - incremental 17.5.0 py_0
        - ipython 7.0.1 py35h24bf2e0_0
        - ipython_genutils 0.2.0 py_1
        - jedi 0.12.1 py35_0
        - jpeg 9c h14c3975_1001
        - kiwisolver 1.0.1 py35h2d50403_2
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran 3.0.0 1
        - libiconv 1.15 h516909a_1005
        - libpng 1.6.37 hed695b0_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.9 h13577e0_2
        - linecache2 1.0.0 py_1
        - llvmlite 0.25.0 py35_0
        - lzo 2.10 h14c3975_1000
        - matplotlib 3.0.0 py35h5429711_0
        - mpi 1.0 mpich
        - mpi4py 2.0.0 py35_2
        - mpich 3.2.1 h26a2512_7
        - ncurses 6.1 hf484d3e_1002
        - networkx 2.3 py_0
        - numba 0.40.0 py35hf8a1672_0
        - numexpr 2.6.6 py35h470a237_1
        - numpy 1.14.6 py35_blas_openblashd3ea46f_200
        - openblas 0.2.20 8
        - openssl 1.0.2r h14c3975_0
        - parso 0.5.1 py_0
        - pcre 8.43 he6710b0_0
        - pexpect 4.6.0 py35_0
        - pickleshare 0.7.5 py35_0
        - pip 18.0 py35_1001
        - prompt_toolkit 2.0.9 py_0
        - pthread-stubs 0.4 h14c3975_1001
        - ptyprocess 0.6.0 py_1001
        - pyasn1 0.4.6 py_0
        - pyasn1-modules 0.2.6 py_0
        - pycparser 2.19 py_0
        - pygments 2.4.2 py_0
        - pyhamcrest 1.9.0 py_2
        - pyopenssl 18.0.0 py35_0
        - pyparsing 2.4.2 py_0
        - pyqt 5.9.2 py35h05f1152_2
        - pytables 3.4.4 py35h4f72b40_1
        - python 3.5.5 h5001a0f_2
        - python-dateutil 2.8.0 py_0
        - pytz 2019.2 py_0
        - pyvtk 0.5.18 py35_0
        - qt 5.9.6 h8703b6f_2
        - readline 7.0 hf8c457e_1001
        - scipy 1.1.0 py35_blas_openblash7943236_201
        - service_identity 18.1.0 py_0
        - setuptools 40.4.3 py35_0
        - shapely 1.6.4 py35h164cb2d_1
        - simplegeneric 0.8.1 py_1
        - sip 4.19.8 py35hf484d3e_1000
        - six 1.11.0 py35_1
        - sparse 0.7.0 py_0
        - sqlite 3.28.0 h8b20d00_0
        - termcolor 1.1.0 py_2
        - tk 8.6.9 hed695b0_1002
        - tornado 5.1.1 py35h470a237_0
        - traceback2 1.4.0 py35_0
        - traitlets 4.3.2 py35_0
        - twisted 18.7.0 py35h470a237_1
        - unittest2 1.1.0 py35h0cb595e_0
        - wcwidth 0.1.7 py_1
        - wheel 0.32.0 py35_1000
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
        - zope.interface 4.5.0 py35h470a237_1
    run:
        - alabaster
        - deepdish
        - future
        - gmsh==3.0.6
        - ipython
        - matplotlib
        - mpi4py==2.0.0
        - networkx
        - numpy
        - pyqt
        - python
        - pyvtk
        - scipy
        - shapely
        - sparse
        - termcolor
        - twisted
        - unittest2
test:
    imports:
        - openbte
about:
    description: For Windows you'll beed to install MSMPI. Install with    conda install
        -c conda-forge -c gromano openbte
    home: The package home page
    license: GPLv2
    license_family: GPL2
    summary: Boltzmann Transport Equation for Phonons
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - romanodev
