{% set name = "openbte" %}
{% set version = "0.9.41" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de78d328dd5432e6fedab2404f13f632dbdafe8128ac39381cfd5faac5d6a7f4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - alabaster
    - deepdish
    - future
    - ipython
    - matplotlib
    - mpi4py
    - numpy
    - pip
    - python
    - pyvtk
    - scipy
    - shapely
    - sparse
    - unittest2
  run:
    - alabaster
    - deepdish
    - future
    - ipython
    - matplotlib
    - mpi4py
    - numpy
    - python
    - pyvtk
    - scipy
    - shapely
    - sparse
    - unittest2

test:
  imports:
    - openbte

about:
  home: The package home page
  license: GPLv2
  license_family: GPL2
  license_file: 
  summary: Boltzmann Transport Equation for Phonons
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
