{% set name = "openbte" %}
{% set version = "0.9.37" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number : 0      
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - alabaster
    - deepdish
    - future
    - ipython
    - matplotlib
    - mpi4py
    - numpy
    - pip
    - python
    - pyvtk
    - scipy
    - shapely
    - sparse
    - termcolor
    - unittest2
    - gmsh  
    - lapack  
  run:
    - alabaster
    - deepdish
    - future
    - ipython
    - matplotlib
    - mpi4py
    - numpy
    - python
    - pyvtk
    - scipy
    - shapely
    - sparse
    - termcolor
    - unittest2
    - gmsh
    - lapack  

test:
  imports:
    - openbte

about:
  home: The package home page
  license: GPLv2
  license_family: GPL2
  license_file: 
  summary: Boltzmann Transport Equation for Phonons
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - romanodev
